export const books = [
  {
    "id": "1",
    "slug": "to-kill-a-mockingbird",
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "category": "Fiction",
    "isbn": "9780061120084",
    "price": 14.49,
    "description": "To Kill a Mockingbird by Harper Lee, a popular fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    "createdAt": "2025-01-02T10:00:00Z",
    "rating": 4.1,
    "ratingsCount": 1500,
    "stock": 11,
    "pages": 208,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "2",
    "slug": "1984",
    "title": "1984",
    "author": "George Orwell",
    "category": "Dystopian",
    "isbn": "9780451524935",
    "price": 15.99,
    "description": "1984 by George Orwell, a popular dystopian book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    "createdAt": "2025-01-03T10:00:00Z",
    "rating": 4.2,
    "ratingsCount": 2000,
    "stock": 12,
    "pages": 216,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "3",
    "slug": "the-great-gatsby",
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "category": "Fiction",
    "isbn": "9780743273565",
    "price": 17.49,
    "description": "The Great Gatsby by F. Scott Fitzgerald, a popular fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    "createdAt": "2025-01-04T10:00:00Z",
    "rating": 4.3,
    "ratingsCount": 2500,
    "stock": 13,
    "pages": 224,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "4",
    "slug": "pride-and-prejudice",
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "category": "Romance",
    "isbn": "9780141439518",
    "price": 18.99,
    "description": "Pride and Prejudice by Jane Austen, a popular romance book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    "createdAt": "2025-01-05T10:00:00Z",
    "rating": 4.4,
    "ratingsCount": 3000,
    "stock": 14,
    "pages": 232,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "5",
    "slug": "the-hobbit",
    "title": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "category": "Fantasy",
    "isbn": "9780547928227",
    "price": 20.49,
    "description": "The Hobbit by J.R.R. Tolkien, a popular fantasy book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    "createdAt": "2025-01-06T10:00:00Z",
    "rating": 4.5,
    "ratingsCount": 3500,
    "stock": 15,
    "pages": 240,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "6",
    "slug": "the-lord-of-the-rings",
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "category": "Fantasy",
    "isbn": "9780618640157",
    "price": 21.99,
    "description": "The Lord of the Rings by J.R.R. Tolkien, a popular fantasy book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
    "createdAt": "2025-01-07T10:00:00Z",
    "rating": 4.6,
    "ratingsCount": 4000,
    "stock": 16,
    "pages": 248,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "7",
    "slug": "harry-potter-sorcerers-stone",
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "category": "Fantasy",
    "isbn": "9780590353427",
    "price": 23.49,
    "description": "Harry Potter and the Sorcerer's Stone by J.K. Rowling, a popular fantasy book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
    "createdAt": "2025-01-08T10:00:00Z",
    "rating": 4.7,
    "ratingsCount": 4500,
    "stock": 17,
    "pages": 256,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "8",
    "slug": "atomic-habits",
    "title": "Atomic Habits",
    "author": "James Clear",
    "category": "Self-Help",
    "isbn": "9780735211292",
    "price": 24.99,
    "description": "Atomic Habits by James Clear, a popular self-help book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    "createdAt": "2025-01-09T10:00:00Z",
    "rating": 4.8,
    "ratingsCount": 5000,
    "stock": 18,
    "pages": 264,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "9",
    "slug": "deep-work",
    "title": "Deep Work",
    "author": "Cal Newport",
    "category": "Productivity",
    "isbn": "9781455586691",
    "price": 26.49,
    "description": "Deep Work by Cal Newport, a popular productivity book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
    "createdAt": "2025-01-10T10:00:00Z",
    "rating": 4.9,
    "ratingsCount": 5500,
    "stock": 19,
    "pages": 272,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "10",
    "slug": "the-alchemist",
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "category": "Fiction",
    "isbn": "9780061122415",
    "price": 27.99,
    "description": "The Alchemist by Paulo Coelho, a popular fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    "createdAt": "2025-01-11T10:00:00Z",
    "rating": 4.0,
    "ratingsCount": 6000,
    "stock": 20,
    "pages": 280,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "11",
    "slug": "dune",
    "title": "Dune",
    "author": "Frank Herbert",
    "category": "Science Fiction",
    "isbn": "9780441172719",
    "price": 29.49,
    "description": "Dune by Frank Herbert, a popular science fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    "createdAt": "2025-01-12T10:00:00Z",
    "rating": 4.1,
    "ratingsCount": 6500,
    "stock": 21,
    "pages": 288,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "12",
    "slug": "the-martian",
    "title": "The Martian",
    "author": "Andy Weir",
    "category": "Science Fiction",
    "isbn": "9780553418026",
    "price": 30.99,
    "description": "The Martian by Andy Weir, a popular science fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
    "createdAt": "2025-01-13T10:00:00Z",
    "rating": 4.2,
    "ratingsCount": 7000,
    "stock": 22,
    "pages": 296,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "13",
    "slug": "sapiens",
    "title": "Sapiens",
    "author": "Yuval Noah Harari",
    "category": "History",
    "isbn": "9780062316097",
    "price": 32.49,
    "description": "Sapiens by Yuval Noah Harari, a popular history book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    "createdAt": "2025-01-14T10:00:00Z",
    "rating": 4.3,
    "ratingsCount": 7500,
    "stock": 23,
    "pages": 304,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "14",
    "slug": "educated",
    "title": "Educated",
    "author": "Tara Westover",
    "category": "Biography",
    "isbn": "9780399590504",
    "price": 33.99,
    "description": "Educated by Tara Westover, a popular biography book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    "createdAt": "2025-01-15T10:00:00Z",
    "rating": 4.4,
    "ratingsCount": 8000,
    "stock": 24,
    "pages": 312,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "15",
    "slug": "becoming",
    "title": "Becoming",
    "author": "Michelle Obama",
    "category": "Biography",
    "isbn": "9781524763138",
    "price": 12.99,
    "description": "Becoming by Michelle Obama, a popular biography book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    "createdAt": "2025-01-16T10:00:00Z",
    "rating": 4.5,
    "ratingsCount": 8500,
    "stock": 25,
    "pages": 320,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "16",
    "slug": "thinking-fast-and-slow",
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "category": "Psychology",
    "isbn": "9780374533557",
    "price": 14.49,
    "description": "Thinking, Fast and Slow by Daniel Kahneman, a popular psychology book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    "createdAt": "2025-01-17T10:00:00Z",
    "rating": 4.6,
    "ratingsCount": 9000,
    "stock": 26,
    "pages": 328,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "17",
    "slug": "rich-dad-poor-dad",
    "title": "Rich Dad Poor Dad",
    "author": "Robert Kiyosaki",
    "category": "Finance",
    "isbn": "9781612680194",
    "price": 15.99,
    "description": "Rich Dad Poor Dad by Robert Kiyosaki, a popular finance book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
    "createdAt": "2025-01-18T10:00:00Z",
    "rating": 4.7,
    "ratingsCount": 9500,
    "stock": 27,
    "pages": 336,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "18",
    "slug": "the-psychology-of-money",
    "title": "The Psychology of Money",
    "author": "Morgan Housel",
    "category": "Finance",
    "isbn": "9780857197689",
    "price": 17.49,
    "description": "The Psychology of Money by Morgan Housel, a popular finance book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    "createdAt": "2025-01-19T10:00:00Z",
    "rating": 4.8,
    "ratingsCount": 10000,
    "stock": 28,
    "pages": 344,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "19",
    "slug": "clean-code",
    "title": "Clean Code",
    "author": "Robert C. Martin",
    "category": "Technology",
    "isbn": "9780132350884",
    "price": 18.99,
    "description": "Clean Code by Robert C. Martin, a popular technology book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    "createdAt": "2025-01-20T10:00:00Z",
    "rating": 4.9,
    "ratingsCount": 10500,
    "stock": 29,
    "pages": 352,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "20",
    "slug": "the-pragmatic-programmer",
    "title": "The Pragmatic Programmer",
    "author": "Andrew Hunt",
    "category": "Technology",
    "isbn": "9780135957059",
    "price": 20.49,
    "description": "The Pragmatic Programmer by Andrew Hunt, a popular technology book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg",
    "createdAt": "2025-01-21T10:00:00Z",
    "rating": 4.0,
    "ratingsCount": 11000,
    "stock": 30,
    "pages": 360,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "21",
    "slug": "you-dont-know-js",
    "title": "You Don't Know JS Yet",
    "author": "Kyle Simpson",
    "category": "Technology",
    "isbn": "9781098124045",
    "price": 21.99,
    "description": "You Don't Know JS Yet by Kyle Simpson, a popular technology book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781098124045-L.jpg",
    "createdAt": "2025-01-22T10:00:00Z",
    "rating": 4.1,
    "ratingsCount": 11500,
    "stock": 31,
    "pages": 368,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "22",
    "slug": "zero-to-one",
    "title": "Zero to One",
    "author": "Peter Thiel",
    "category": "Business",
    "isbn": "9780804139298",
    "price": 23.49,
    "description": "Zero to One by Peter Thiel, a popular business book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    "createdAt": "2025-01-23T10:00:00Z",
    "rating": 4.2,
    "ratingsCount": 12000,
    "stock": 32,
    "pages": 376,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "23",
    "slug": "the-lean-startup",
    "title": "The Lean Startup",
    "author": "Eric Ries",
    "category": "Business",
    "isbn": "9780307887894",
    "price": 24.99,
    "description": "The Lean Startup by Eric Ries, a popular business book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    "createdAt": "2025-01-24T10:00:00Z",
    "rating": 4.3,
    "ratingsCount": 12500,
    "stock": 33,
    "pages": 384,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "24",
    "slug": "good-to-great",
    "title": "Good to Great",
    "author": "Jim Collins",
    "category": "Business",
    "isbn": "9780066620992",
    "price": 26.49,
    "description": "Good to Great by Jim Collins, a popular business book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg",
    "createdAt": "2025-01-25T10:00:00Z",
    "rating": 4.4,
    "ratingsCount": 13000,
    "stock": 34,
    "pages": 392,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "25",
    "slug": "the-7-habits",
    "title": "The 7 Habits of Highly Effective People",
    "author": "Stephen Covey",
    "category": "Self-Help",
    "isbn": "9781982137274",
    "price": 27.99,
    "description": "The 7 Habits of Highly Effective People by Stephen Covey, a popular self-help book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
    "createdAt": "2025-01-26T10:00:00Z",
    "rating": 4.5,
    "ratingsCount": 13500,
    "stock": 35,
    "pages": 400,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "26",
    "slug": "the-subtle-art",
    "title": "The Subtle Art of Not Giving a F*ck",
    "author": "Mark Manson",
    "category": "Self-Help",
    "isbn": "9780062457714",
    "price": 29.49,
    "description": "The Subtle Art of Not Giving a F*ck by Mark Manson, a popular self-help book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    "createdAt": "2025-01-27T10:00:00Z",
    "rating": 4.6,
    "ratingsCount": 14000,
    "stock": 36,
    "pages": 408,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "27",
    "slug": "gone-girl",
    "title": "Gone Girl",
    "author": "Gillian Flynn",
    "category": "Thriller",
    "isbn": "9780307588371",
    "price": 30.99,
    "description": "Gone Girl by Gillian Flynn, a popular thriller book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
    "createdAt": "2025-01-28T10:00:00Z",
    "rating": 4.7,
    "ratingsCount": 14500,
    "stock": 37,
    "pages": 416,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "28",
    "slug": "the-girl-with-the-dragon-tattoo",
    "title": "The Girl with the Dragon Tattoo",
    "author": "Stieg Larsson",
    "category": "Mystery",
    "isbn": "9780307454546",
    "price": 32.49,
    "description": "The Girl with the Dragon Tattoo by Stieg Larsson, a popular mystery book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg",
    "createdAt": "2025-01-01T10:00:00Z",
    "rating": 4.8,
    "ratingsCount": 15000,
    "stock": 38,
    "pages": 424,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "29",
    "slug": "the-da-vinci-code",
    "title": "The Da Vinci Code",
    "author": "Dan Brown",
    "category": "Mystery",
    "isbn": "9780307474278",
    "price": 33.99,
    "description": "The Da Vinci Code by Dan Brown, a popular mystery book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    "createdAt": "2025-01-02T10:00:00Z",
    "rating": 4.9,
    "ratingsCount": 15500,
    "stock": 39,
    "pages": 432,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "30",
    "slug": "angels-and-demons",
    "title": "Angels & Demons",
    "author": "Dan Brown",
    "category": "Thriller",
    "isbn": "9780743493468",
    "price": 12.99,
    "description": "Angels & Demons by Dan Brown, a popular thriller book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780743493468-L.jpg",
    "createdAt": "2025-01-03T10:00:00Z",
    "rating": 4.0,
    "ratingsCount": 16000,
    "stock": 40,
    "pages": 440,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "31",
    "slug": "the-book-thief",
    "title": "The Book Thief",
    "author": "Markus Zusak",
    "category": "Historical Fiction",
    "isbn": "9780375842207",
    "price": 14.49,
    "description": "The Book Thief by Markus Zusak, a popular historical fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    "createdAt": "2025-01-04T10:00:00Z",
    "rating": 4.1,
    "ratingsCount": 16500,
    "stock": 41,
    "pages": 448,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "32",
    "slug": "all-the-light-we-cannot-see",
    "title": "All the Light We Cannot See",
    "author": "Anthony Doerr",
    "category": "Historical Fiction",
    "isbn": "9781501173219",
    "price": 15.99,
    "description": "All the Light We Cannot See by Anthony Doerr, a popular historical fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781501173219-L.jpg",
    "createdAt": "2025-01-05T10:00:00Z",
    "rating": 4.2,
    "ratingsCount": 17000,
    "stock": 42,
    "pages": 456,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "33",
    "slug": "the-kite-runner",
    "title": "The Kite Runner",
    "author": "Khaled Hosseini",
    "category": "Fiction",
    "isbn": "9781594631931",
    "price": 17.49,
    "description": "The Kite Runner by Khaled Hosseini, a popular fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    "createdAt": "2025-01-06T10:00:00Z",
    "rating": 4.3,
    "ratingsCount": 17500,
    "stock": 43,
    "pages": 464,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "34",
    "slug": "a-thousand-splendid-suns",
    "title": "A Thousand Splendid Suns",
    "author": "Khaled Hosseini",
    "category": "Fiction",
    "isbn": "9781594483851",
    "price": 18.99,
    "description": "A Thousand Splendid Suns by Khaled Hosseini, a popular fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781594483851-L.jpg",
    "createdAt": "2025-01-07T10:00:00Z",
    "rating": 4.4,
    "ratingsCount": 18000,
    "stock": 44,
    "pages": 472,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "35",
    "slug": "the-fault-in-our-stars",
    "title": "The Fault in Our Stars",
    "author": "John Green",
    "category": "Young Adult",
    "isbn": "9780142424179",
    "price": 20.49,
    "description": "The Fault in Our Stars by John Green, a popular young adult book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780142424179-L.jpg",
    "createdAt": "2025-01-08T10:00:00Z",
    "rating": 4.5,
    "ratingsCount": 18500,
    "stock": 45,
    "pages": 480,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "36",
    "slug": "the-hunger-games",
    "title": "The Hunger Games",
    "author": "Suzanne Collins",
    "category": "Young Adult",
    "isbn": "9780439023481",
    "price": 21.99,
    "description": "The Hunger Games by Suzanne Collins, a popular young adult book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
    "createdAt": "2025-01-09T10:00:00Z",
    "rating": 4.6,
    "ratingsCount": 19000,
    "stock": 46,
    "pages": 488,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "37",
    "slug": "catching-fire",
    "title": "Catching Fire",
    "author": "Suzanne Collins",
    "category": "Young Adult",
    "isbn": "9780439023498",
    "price": 23.49,
    "description": "Catching Fire by Suzanne Collins, a popular young adult book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780439023498-L.jpg",
    "createdAt": "2025-01-10T10:00:00Z",
    "rating": 4.7,
    "ratingsCount": 19500,
    "stock": 47,
    "pages": 496,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "38",
    "slug": "mockingjay",
    "title": "Mockingjay",
    "author": "Suzanne Collins",
    "category": "Young Adult",
    "isbn": "9780439023511",
    "price": 24.99,
    "description": "Mockingjay by Suzanne Collins, a popular young adult book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780439023511-L.jpg",
    "createdAt": "2025-01-11T10:00:00Z",
    "rating": 4.8,
    "ratingsCount": 20000,
    "stock": 48,
    "pages": 504,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "39",
    "slug": "the-name-of-the-wind",
    "title": "The Name of the Wind",
    "author": "Patrick Rothfuss",
    "category": "Fantasy",
    "isbn": "9780756404741",
    "price": 26.49,
    "description": "The Name of the Wind by Patrick Rothfuss, a popular fantasy book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
    "createdAt": "2025-01-12T10:00:00Z",
    "rating": 4.9,
    "ratingsCount": 20500,
    "stock": 49,
    "pages": 512,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "40",
    "slug": "mistborn",
    "title": "Mistborn",
    "author": "Brandon Sanderson",
    "category": "Fantasy",
    "isbn": "9780765311788",
    "price": 27.99,
    "description": "Mistborn by Brandon Sanderson, a popular fantasy book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg",
    "createdAt": "2025-01-13T10:00:00Z",
    "rating": 4.0,
    "ratingsCount": 21000,
    "stock": 10,
    "pages": 520,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "41",
    "slug": "the-way-of-kings",
    "title": "The Way of Kings",
    "author": "Brandon Sanderson",
    "category": "Fantasy",
    "isbn": "9780765365279",
    "price": 29.49,
    "description": "The Way of Kings by Brandon Sanderson, a popular fantasy book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780765365279-L.jpg",
    "createdAt": "2025-01-14T10:00:00Z",
    "rating": 4.1,
    "ratingsCount": 21500,
    "stock": 11,
    "pages": 528,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "42",
    "slug": "project-hail-mary",
    "title": "Project Hail Mary",
    "author": "Andy Weir",
    "category": "Science Fiction",
    "isbn": "9780593135204",
    "price": 30.99,
    "description": "Project Hail Mary by Andy Weir, a popular science fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    "createdAt": "2025-01-15T10:00:00Z",
    "rating": 4.2,
    "ratingsCount": 22000,
    "stock": 12,
    "pages": 536,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "43",
    "slug": "ready-player-one",
    "title": "Ready Player One",
    "author": "Ernest Cline",
    "category": "Science Fiction",
    "isbn": "9780307887443",
    "price": 32.49,
    "description": "Ready Player One by Ernest Cline, a popular science fiction book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780307887443-L.jpg",
    "createdAt": "2025-01-16T10:00:00Z",
    "rating": 4.3,
    "ratingsCount": 22500,
    "stock": 13,
    "pages": 544,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "44",
    "slug": "the-power-of-habit",
    "title": "The Power of Habit",
    "author": "Charles Duhigg",
    "category": "Self-Help",
    "isbn": "9780812981605",
    "price": 33.99,
    "description": "The Power of Habit by Charles Duhigg, a popular self-help book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780812981605-L.jpg",
    "createdAt": "2025-01-17T10:00:00Z",
    "rating": 4.4,
    "ratingsCount": 23000,
    "stock": 14,
    "pages": 552,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "45",
    "slug": "start-with-why",
    "title": "Start With Why",
    "author": "Simon Sinek",
    "category": "Business",
    "isbn": "9781591846444",
    "price": 12.99,
    "description": "Start With Why by Simon Sinek, a popular business book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg",
    "createdAt": "2025-01-18T10:00:00Z",
    "rating": 4.5,
    "ratingsCount": 23500,
    "stock": 15,
    "pages": 560,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "46",
    "slug": "hooked",
    "title": "Hooked",
    "author": "Nir Eyal",
    "category": "Business",
    "isbn": "9781591847786",
    "price": 14.49,
    "description": "Hooked by Nir Eyal, a popular business book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781591847786-L.jpg",
    "createdAt": "2025-01-19T10:00:00Z",
    "rating": 4.6,
    "ratingsCount": 24000,
    "stock": 16,
    "pages": 568,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "47",
    "slug": "rework",
    "title": "Rework",
    "author": "Jason Fried",
    "category": "Business",
    "isbn": "9780307463746",
    "price": 15.99,
    "description": "Rework by Jason Fried, a popular business book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9780307463746-L.jpg",
    "createdAt": "2025-01-20T10:00:00Z",
    "rating": 4.7,
    "ratingsCount": 24500,
    "stock": 17,
    "pages": 576,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "48",
    "slug": "the-code-breaker",
    "title": "The Code Breaker",
    "author": "Walter Isaacson",
    "category": "Biography",
    "isbn": "9781982115852",
    "price": 17.49,
    "description": "The Code Breaker by Walter Isaacson, a popular biography book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781982115852-L.jpg",
    "createdAt": "2025-01-21T10:00:00Z",
    "rating": 4.8,
    "ratingsCount": 25000,
    "stock": 18,
    "pages": 584,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "49",
    "slug": "steve-jobs",
    "title": "Steve Jobs",
    "author": "Walter Isaacson",
    "category": "Biography",
    "isbn": "9781451648539",
    "price": 18.99,
    "description": "Steve Jobs by Walter Isaacson, a popular biography book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
    "createdAt": "2025-01-22T10:00:00Z",
    "rating": 4.9,
    "ratingsCount": 25500,
    "stock": 19,
    "pages": 592,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  },
  {
    "id": "50",
    "slug": "elon-musk",
    "title": "Elon Musk",
    "author": "Walter Isaacson",
    "category": "Biography",
    "isbn": "9781982181284",
    "price": 20.49,
    "description": "Elon Musk by Walter Isaacson, a popular biography book.",
    "coverImageUrl": "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg",
    "createdAt": "2025-01-23T10:00:00Z",
    "rating": 4.0,
    "ratingsCount": 26000,
    "stock": 20,
    "pages": 600,
    "publisher": "Various Publishers",
    "language": "English",
    "sellerEmail": ""
  }
];


export async function fetchBooks() {
    await new Promise((resolve) => setTimeout(resolve, 500));
    return [...books];
}

export async function getBookBySlug(slug: string) {
  await new Promise((r) => setTimeout(r, 500));

  return books.find((book) => book.slug === slug);
}

export async function getRecommendedBooks() {
  await new Promise((r) => setTimeout(r, 3000));

  return books.slice(0, 4);
}